### ISSUE TITLE
Issues with accents

### ISSUE THREAD

**Issue by notaryzw3b** [MinnDevelopment/discord-webhooks#12]
Hi !

Here in france we use characters likes "é", "à", "ù"

And it doesn't works with DiscordWebhooks, idk if its me bc I use webhooks with an Habbo Emulator, is it this?

Thanks

**Comment by Andre601** [comment]
I think it's caused by how you encode the final jar/code.
I'm pretty sure this lib supports those characters as long as you have a proper encoding like UTF-8.
In addition, do you give 0 info on how to reproduce this issue. Code snippets, the text used, etc.

**Comment by notaryzw3b** [comment]
I've found !

in my .bat i've written -Dfile.enfoding=UTF-8 and not encoding, here is the problem.

Thanks :)
