### ISSUE TITLE
Logging and exception improvements

### ISSUE THREAD

**Issue by celandro** [MinnDevelopment/discord-webhooks#18]
Currently logging is difficult to configure as there are multiple classifications of errors being passed at different times (asynchronously). Exceptions also are also generic, and there is no clear way to handle fairly common use cases such as invalid webhook urls and deleted webhooks.

Current logging:
1. `LOG.debug("Backing off queue for {}", delay);`
1. `LOG.error("Sending a webhook message failed with non-OK http response", exception);`
1. `LOG.error("Encountered 429, retrying after {}", delay);`
1. `LOG.debug("Failed to update buckets due to unsuccessful response with code: {} and body: \n{}",                          response.code(), new IOUtil.Lazy(() -> new String(IOUtil.readAllBytes(IOUtil.getBody(response)))));`
1. ` LOG.error("Could not read http response", ex);`

My thoughts on each of the log lines:

1. This is a rate limit error and should mention that you are being rate limited at the bucket level. Suggest WARN level
2. This should be split up into multiple categories of exception for example `Sending a webhook message failed with non-OK http response club.minnced.discord.webhook.exception.HttpException: Request returned failure 404: {"message": "Unknown Webhook", "code": 10015}` should be warn level and throw an UnknownWebhookException. Other common errors such as 400 or 500 should also have their own exception classes if you know what causes them. 400 and 500 I would suggest error level.
3. This is also a rate limit error and should say so explicitly. Suggest warn level
4. This seems a duplicate of #2 
5. JSONException would seem to be an error in your own client library. IOException I think is fine to throw as is.

Even with these changes, the errors will be intermingled and difficult to separate what to log. For example, most of these errors are actually returned in the Future and should be handled and logged by the clients so you would want to turn these errors off.  The rate limit warnings on the other hand are never sent to the client so you need to keep the logs on.   Highly suggest refactoring the code into multiple classes with different loggers. Alternatively, make different loggers for each of the classification of errors so that they can be configured properly.

Arguably, client libraries should never log errors and should simply provide callbacks for the client to perform the logging themselves. This may not be practical for the target audience for this library but I did want to put that option out there.

Overall, I love this library and am willing to make these changes in a PR if you wish but at high volume it becomes excessively noisy.

**Comment by MinnDevelopment** [comment]
> This is a rate limit error and should mention that you are being rate limited at the bucket level. Suggest WARN level

Not really an error, this is normal operation and happens constantly.

> This should be split up into multiple categories of exception for example Sending a webhook message failed with non-OK http response club.minnced.discord.webhook.exception.HttpException: Request returned failure 404: {"message": "Unknown Webhook", "code": 10015} should be warn level and throw an UnknownWebhookException. Other common errors such as 400 or 500 should also have their own exception classes if you know what causes them. 400 and 500 I would suggest error level

No, these are all errors and are logged as such. Handling specific API errors is up to the user and I don't see a lot of value into making 300 different exception classes when you can simply check the code and body provided by the exception. An unknown webhook error will always be code 404.

> This is also a rate limit error and should say so explicitly. Suggest warn level

It is already logged on error level, hitting the 429 is an error and must be avoided.

> LOG.debug("Failed to update buckets due to unsuccessful response with code: {} and body: \n{}", response.code(), new IOUtil.Lazy(() -> new String(IOUtil.readAllBytes(IOUtil.getBody(response)))));

This log of headers is rarely useful, this its not logged on warn.

> JSONException would seem to be an error in your own client library. IOException I think is fine to throw as is.

You can't throw from an async context. This makes no sense.


Overall, I reject all your suggestions because I've put a lot of thought into this library to make logging logical and appropriate for the common scenarios. The `CompletableFuture` class ignores all exceptions by default, so it is logical to also log them directly. The reason why rate limit errors do not propogate to the future, is because the requests are retried automatically and a user can't do anything with this. Worst-case, the user will even try to retry a request that is already being retried by the library.

Ever since this library has been published, I've used it extensively for various purposes and never had any issues with the logging or exception handling. For any further logging configurations, to filter and otherwise alter the output of the library, I suggest using a proper SLF4J implementation which can do this for you, through filters/encoders/adapters.


> Exceptions also are also generic, and there is no clear way to handle fairly common use cases such as invalid webhook urls and deleted webhooks.

This is simply untrue. The HttpException gives you direct access to the HTTP error codes, and thus is completely usable for any special handling like 404 (deleted webhook). The library outright rejects invalid URLs before it even gets to use them.

**Comment by celandro** [comment]
I understand your point of view, however the root problem that perhaps I did not explain is simply one of what to do in case of timeouts and 429s. 

Basically, if a message does not send within 30s I want to be able to drop messages and slow them down in general. There is currently no way to do this. 

I wrote some example code to show the issue:
```
// Webhook cluster
    @Bean
    public WebhookCluster webhookCluser(@Value("${raidParty.webhook.threadPoolSize}") int threadPoolSize ) {
        WebhookCluster cluster = new WebhookCluster(10);
        cluster.setDefaultDaemon(true);
        ThreadFactory threadFactory = (job) -> {
            Thread thread = new Thread(job);
            thread.setName("WebhookCluster");
            thread.setDaemon(true);
           return thread; 
        };
        cluster.setDefaultExecutorService(Executors.newScheduledThreadPool(threadPoolSize, threadFactory));
                
        cluster.setDefaultThreadFactory(threadFactory);
        
        return cluster;
    }
// client factory
public class WebhookClientFactory extends CacheLoader<String, WebhookClient> {
    private final WebhookCluster cluster;

    public WebhookClientFactory(WebhookCluster cluster) {
        this.cluster = cluster;
    }

    public WebhookClient load(String url) {
        Matcher matcher = WebhookClientBuilder.WEBHOOK_PATTERN.matcher(url);
        if (!matcher.matches()) {
            throw new IllegalArgumentException("Failed to parse webhook URL");
        }
        long id = Long.parseUnsignedLong(matcher.group(1));
        String token = matcher.group(2);
        WebhookClient client = cluster.newBuilder(id, token).build();
        cluster.addWebhooks(client);
        return client;
    }
}



    void sendRemoteHelpMessages(Notification change, Optional<DiscordGuild> guild, String language, List<DiscordGuild> helperGuilds) {
        WebhookMessage message = createRemoteHelpMessage(change, guild, i18NextServer.getI18Next(language));
        log.info("Sending {} discord raid request for {} to {} servers", language, change.getId(), helperGuilds.size());
        for (DiscordGuild helperGuild: helperGuilds) {
            try {
                //This does not cancel queues messages as you would hope
                sendRemoteHelpMessage(message, helperGuild).orTimeout(globalNotificationTimeoutMs, TimeUnit.MILLISECONDS).whenCompleteAsync((result,e) -> {
                    if (e != null) {
                        if (e instanceof HttpException) {
                            HttpException he = (HttpException) e;
                            if (he.getCode() == INVALID_WEBHOOK_CODE) {
                                log.error("Invalid or deleted webhook for {}, removing", helperGuild);
                                webhookClients.invalidate(helperGuild.getWebhookUrl());
                                helperGuild.setWebhookUrl(null);
                                discordService.updateDiscordGuild(helperGuild);
                                return;
                            }
                        } else if (e instanceof TimeoutException) {
                            log.warn("Time out after {}ms sending {} to {}", globalNotificationTimeoutMs ,change.getRaidPartyId(), helperGuild);
                        } else {
                            log.error("Could not send {} to {}",change.getRaidPartyId(),helperGuild,e);
                        }
                    }
                });
            } catch (ExecutionException | RuntimeException e) {
                log.error("Not retrying " + change.getId() + ": Could not send discord raid request for " + helperGuild, e);
            }
        }
    }

//actual send code:
    LoadingCache<String, WebhookClient> webhookClients;
...
        webhookClients = CacheBuilder.newBuilder().build(new WebhookClientFactory(cluster));
...
    CompletableFuture<ReadonlyMessage> sendRemoteHelpMessage(WebhookMessage webhookMessage,  DiscordGuild helperGuild) throws ExecutionException {
            return webhookClients.get(helperGuild.getWebhookUrl()).send(webhookMessage);
    }
```
When run in a for loop size 100, the following messages occur:
```
12:24:05.103 [gcp-pubsub-subscriber4] INFO  c.p.f.p.RaidPartyGlobalDiscordNotificationPubSub - Sending en-US discord raid request for 87 to 2 servers
//repeated 100 times...

12:24:25.137 [WebhookCluster] ERROR c.m.discord.webhook.WebhookClient - Encountered 429, retrying after 40090

12:24:35.062 [ForkJoinPool.commonPool-worker-61] WARN  c.p.f.p.RaidPartyGlobalDiscordNotificationPubSub - Time out after 30000ms sending 87 to DiscordGuild [id=1234, ...]
//repeated 85 times

12:25:23.336 [WebhookCluster] ERROR c.m.discord.webhook.WebhookClient - Encountered 429, retrying after 42039
12:26:23.202 [WebhookCluster] ERROR c.m.discord.webhook.WebhookClient - Encountered 429, retrying after 42292
```
All messages are sent to the webhook despite the completeablefuture being cancelled.

Looking through the code, you appear to be checking for the cancellation flag. Am I doing something wrong?

I'd at least like to contribute back some advanced configuration docs for people who want to control their own error handling.

**Comment by celandro** [comment]
Found the issue..

    private boolean executePair(@Async.Execute Request req) {
        if (req.future.isCancelled()) {

should be

    private boolean executePair(@Async.Execute Request req) {
        if (req.future.isCompletedExceptionally()) {

as TimeoutException is not a CancellationException

Will open a separate bug ticket
