### ISSUE TITLE
Retrying after 429 when sending a file results in an empty file

### ISSUE THREAD

**Issue by Bungeefan** [MinnDevelopment/discord-webhooks#23]
When I am hitting the Rate limit and receiving a 429 while sending a message with an attachment, it retries after it but then the file upload breaks, and it results in a 0 byte file in the discord client.

I tested some things and couldn't get it working when hitting the limit although it could be also an issue on discord's side.

Would be glad if somebody could check this behavior too.

**Comment by Bungeefan** [comment]
![grafik](https://user-images.githubusercontent.com/39010966/102695396-5f012380-4227-11eb-8250-423e8b2a3d9a.png)

**Comment by MinnDevelopment** [comment]
Is this fixed with `0.5.4-rc`?

**Comment by Bungeefan** [comment]
Yep tested it and it works for me. Thanks for the fast fix.
