### ISSUE TITLE
CloudFlare Ratelimits

### ISSUE THREAD

**Issue by Shea4** [MinnDevelopment/discord-webhooks#25]
I was just wondering if you handle cloudflare bans, because yesterday I hit a cloudflare ban and it seemed the library kept accumulating requests and continuosly tried to send them instead of falling back and waiting for the ban to end which meant I was just guaranteed to get banned for the next hour especially with the amount of requests it was accumulating. So not sure if this is due to the library not handling cloudflare ratelimits or if it has something to do with something else.
![image](https://user-images.githubusercontent.com/38985791/107117463-71382f00-6872-11eb-9250-983b64e93633.png)

**Comment by MinnDevelopment** [comment]
Yes, cloudflare rate limits are handled just like discord rate limits are. There is a `Retry-After` header which is handled by each WebhookClient [here](https://github.com/MinnDevelopment/discord-webhooks/blob/d2d8cd425c23f54f8d93dc3fb3668af6939b4321/src/main/java/club/minnced/discord/webhook/WebhookClient.java#L647-L658).

**Comment by Shea4** [comment]
Thanks for the clarification, do you have any idea on why it may not have fallen back in my case then?

**Comment by MinnDevelopment** [comment]
You either used an outdated version of the library, or you used multiple webhook clients that don't share rate limit information and all hit the same rate limit.

**Comment by Shea4** [comment]
I see, I'll have a look into that thanks for the help
