### ISSUE TITLE
WebhookClient process still running after its closure

### ISSUE THREAD

**Issue by youp0214** [MinnDevelopment/discord-webhooks#26]
I tried to run a simple code to test my webhook. I did succeed at sending my message but the program kept running after it and i also received an SLF4 error. dunno why

code: 

```java
var url = "my webhook link";
try (WebhookClient webhook = WebhookClient.withUrl(url)) {
  webhook.send("test").thenRun(() -> {
    System.out.println("message sent");
  });
}
````

output:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
message sent
```

i also tried by explicitly closing the webhookclient without using the try(){   } statement but the issue still persist

I'm using intellij and jdk 11.0.10
library version i'm using is 0.5.5-rc

**Comment by Toadless** [comment]
SLF4 has nothing to do with discord-webhooks it's a logging lib.

**Comment by youp0214** [comment]
What should i do ?

**Comment by MinnDevelopment** [comment]
This is because the OkHTTP client creates a thread which takes a bit longer to timeout. If you configure your own OkHTTP client you can use

```java
client.connectionPool().evictAll();
client.dispatcher().executorService().shutdown();
```

**Comment by cedar01** [comment]
@MinnDevelopment OkHTTP cannot be injected. How can I config my own Okhttp client?
