### ISSUE TITLE
Question about your queue

### ISSUE THREAD

**Issue by skateboard** [MinnDevelopment/discord-webhooks#28]
I was reading through [WebhookClient](https://github.com/MinnDevelopment/discord-webhooks/blob/master/src/main/java/club/minnced/discord/webhook/WebhookClient.java) and I was wondering after you send the first initial 5 webhooks will it wait to send the 6ith? 

I made some mock code

```java
WebhookClient client = WebhookClient.withUrl("WEBHOOK_URL");

for(int i = 0; i < 6; i++) {
   client.send("test #" + i);
}
````

after the 5th one I get
```
21:06:15.009 [Webhook-RateLimit Thread WebhookID: WEBHOOK_ID] DEBUG club.minnced.discord.webhook.WebhookClient - Backing off queue for 1999
```

but the 6ith is never sent? after waiting sometime it never sent so I was wondering if its setup to send after the wait or something.

**Comment by MinnDevelopment** [comment]
The request will be delayed by [backoffQueue](https://github.com/MinnDevelopment/discord-webhooks/blob/b6c19efa690dd310649f9f1172e717e35c162410/src/main/java/club/minnced/discord/webhook/WebhookClient.java#L550-L555). The only reason why it wouldn't send would be if you shutdown the executor/webhook client.

I tried your code and it works as expected:

![image](https://user-images.githubusercontent.com/18090140/110476081-e2713900-80e1-11eb-8b7e-93e62539406c.png)

**Comment by skateboard** [comment]
That's extremely weird I only get to test #4
