### ISSUE TITLE
Issue with gradle implementation

### ISSUE THREAD

**Issue by DSlyDog** [MinnDevelopment/discord-webhooks#29]
Hi,

I recently transferred one of my discord bot projects to gradle. When I try to compile it with the dependencies I get an error.

`org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':jar
Caused by: org.gradle.api.GradleException: Could not expand ZIP 'C:\Users\drews\.gradle\caches\modules-2\files-2.1\club.minnced\opus-java\1.0.4\596995aaf2f5b5091c4d251fdc11fa62680cc59e\opus-java-1.0.4.pom''
Caused by: java.util.zip.ZipException: archive is not a ZIP archive`

It looks like a .pom file (which is for maven) is put into the opus folder and gradle tries to open that like a jar file. I'm not sure if this is something you have control over, but it only happens for this dependency.

**Comment by MCOfficer** [comment]
Can you post your gradle file, specifically the dependencies section?

**Comment by MinnDevelopment** [comment]
This is not a dependency of this library. You have a POM dependency that you are trying to unzip because it is on your compile classpath.

**Comment by DSlyDog** [comment]
Okay, but I copied the dependency listing for gradle on the readme. What should I be using instead?

This is my gradle

`plugins {
    id 'java'
}

group 'net.whispwriting'
version '1.3'

configurations{
    dependencies
}

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    implementation 'net.dv8tion:JDA:4.2.0_241'
    compile("club.minnced:discord-webhooks:0.5.6")
    implementation 'com.googlecode.json-simple:json-simple:1.1.1'
    implementation 'com.sedmelluq:lavaplayer:1.3.73'
}

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes(
                'Main-Class': 'net.whispwriting.lotus.Main'
        )
    }

    from {
        configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
        configurations.runtimeClasspath.collect {it.isDirectory() ? it : zipTree(it)}
    }
}`

**Comment by MinnDevelopment** [comment]
Instead of manually compiling your fat jar you should use [shadow](https://github.com/johnrengelman/shadow). You currently treat any file on the classpath as if it was a jar without any checks. That is simply wrong.
