### ISSUE TITLE
footer and author icon url not working - output shows it as iconUrl instead of icon_url

### ISSUE THREAD

**Issue by dan-dr** [MinnDevelopment/discord-webhooks#43]
```java
// add author
embedBuilder.setAuthor(new EmbedAuthor("Author", "https://example.com/png.png", "https://example.com"));

// ... later after creating a message
webhookMessage.getBody().writeTo(buffer);
LOGGER.debug("getBody: " + buffer.readUtf8());

//in the output i see
"author":{"name":"Author","iconUrl":"https://example.com/png.png","url":"https://example.com"}
```
I believe that's what's sent to discord. it should be "icon_url", and so the icon isn't visible on my embed as a result.
Maybe a json library conflict?

**Comment by MinnDevelopment** [comment]
I think your issue is that you have a severely outdated version of the org.json dependency. This library needs at least [20190722](https://github.com/stleary/JSON-java/releases/tag/20190722) which added [JSONPropertyName](https://github.com/stleary/JSON-java/pull/406).

**Comment by dan-dr** [comment]
Correct
