### ISSUE TITLE
cannot enter string in #setTitle

### ISSUE THREAD

**Issue by portalthree** [MinnDevelopment/discord-webhooks#51]
```  java
WebhookEmbed embed = new WebhookEmbedBuilder()
     .setThumbnailUrl(headURL)
     .setColor(0x55e9e9)
     .setTitle("This is a title")
     .setDescription("This is a description")
     .build();
```
returns the error:

Required type: EmbedTitle
Provided: String

**Comment by Andre601** [comment]
> Required type: Embed Title

The error tells you exactly what is wrong. It expects a specific type, in this case `EmbedTitle` and you provide it with a String.

Setting a embed title in discord-webhooks isn't the same as setting one in JDA. Here you need to create a new instance of EmbedTitle to use.

**Comment by portalthree** [comment]
yep figured it out!
```java
WebhookEmbed embed = new WebhookEmbedBuilder()
                .setThumbnailUrl(headURL)
                .setColor(0x55e9e9)
                .setTitle(new WebhookEmbed.EmbedTitle("This is a title.",""))
                .setDescription("This is a description")
                .build();
``` i'd recommend adding documentation for it

**Comment by MinnDevelopment** [comment]
There is documentation for it: https://github.com/MinnDevelopment/discord-webhooks/blob/a8998393d8836dc899989e044a04ca22dbdb4f93/src/main/java/club/minnced/discord/webhook/send/WebhookEmbedBuilder.java#L198-L208
