### ISSUE TITLE
Failed to parse webhook URL

### ISSUE THREAD

**Issue by Onii-Chan-Discord** [MinnDevelopment/discord-webhooks#55]
I have:
```
private val shardHook = WebhookClientBuilder("https://canary.discord.com/api/webhooks/{MY_CHANNEL_ID}/{MY_WEBHOOK_TOKEN}").build()
```
But it fails to parse the webhook url I copied it from discord in channel settings, I've tried the webhook id and token, but all of three of don't work

Error:
```
Caused by: java.lang.IllegalArgumentException: Failed to parse webhook URL
        at club.minnced.discord.webhook.WebhookClientBuilder.<init>(WebhookClientBuilder.java:84)
        at bot.hibikibot.utils.WebhookManager.<clinit>(WebhookManager.kt:13)
        ... 26 common frames omitted
```

**Comment by TopiSenpai** [comment]
I'd imagine the lib expects not a `canary.` url

**Comment by TopiSenpai** [comment]
Looking at the source code it should parse even the canary url https://github.com/MinnDevelopment/discord-webhooks/blob/8f2b640d0c85310fcf7cc6bc4984e342a4b54a10/src/main/java/club/minnced/discord/webhook/WebhookClientBuilder.java#L46

**Comment by Onii-Chan-Discord** [comment]
Ah my bad, I forget to mention, I've also tried it without the canary.

**Comment by MinnDevelopment** [comment]
I can't reproduce this issue by copying a URL from the client. I get a working webhook client builder. Can you provide the actual URL that is failing here? You can create a new webhook and delete the one you posted.

**Comment by Onii-Chan-Discord** [comment]
Sure, the url I'm was using was https://canary.discord.com/api/webhooks/930347045565399071/VW1SneKXKZhHaXfNTKv-WZ0ylhhUZC6wcX1aeDm4_x4_lBBUg0qK7n3ZXSJkIGfaINGD

**Comment by MinnDevelopment** [comment]
That URL works for me:

```java
WebhookClientBuilder builder = new WebhookClientBuilder("https://canary.discord.com/api/webhooks/930347045565399071/VW1SneKXKZhHaXfNTKv-WZ0ylhhUZC6wcX1aeDm4_x4_lBBUg0qK7n3ZXSJkIGfaINGD")

System.out.println(builder.build().getUrl())
```

**Comment by Onii-Chan-Discord** [comment]
That's weird, I wonder what I'm doing wrong then.

**Comment by MinnDevelopment** [comment]
In any case, as a fallback you can use `new WebhookClientBuilder(id, token)` instead.

**Comment by Onii-Chan-Discord** [comment]
Ok, I'll try that thank you!

**Comment by Onii-Chan-Discord** [comment]
Using the ID and token seems to have done the trick, thank you for your help!

I'll also be closing this now.
