### ISSUE TITLE
Issue with discord webhook proxy services

### ISSUE THREAD

**Issue by caoli5288** [MinnDevelopment/discord-webhooks#65]
Hard coded `discord.com` in WebhookClient, which results in not supporting any third-party services like https://hooks.hyra.io/ or any alternatives.

Please fix it, it's important in some places. :-)

**Comment by MinnDevelopment** [comment]
You don't need a rate-limit proxy for this library. It already handles them for you.

**Comment by caoli5288** [comment]
Because of my ISP does not allow direct access to discord, not for ate-limit proxy

**Comment by MinnDevelopment** [comment]
Then you should use an HTTP CONNECT proxy, this can be done by setting a custom OkHttpClient with [WebhookClientBuilder#seHttpClient](https://minndevelopment.github.io/discord-webhooks/club/minnced/discord/webhook/WebhookClientBuilder.html#setHttpClient(okhttp3.OkHttpClient)).

See: https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/proxy/
