### ISSUE TITLE
shadowJar command not found

### ISSUE THREAD

**Issue by Iprobablyhack** [MinnDevelopment/discord-webhooks#66]
Tried to use ./gradlew shadowJar (./ because im on mac) and it failed because shadowJar command was "not found"
Im probably just dumb, but if you could help me I would be very happy
BTW im using this for a minecraft mod, if that info helps.

**Comment by Andre601** [comment]
Do you actually have the shadowJar plugin added to your build.gradle setup?
This is certainly not an issue with Webhooks as ShadowJar isn't from it, but a separate thing.

**Comment by Iprobablyhack** [comment]
> Do you actually have the shadowJar plugin added to your build.gradle setup? This is certainly not an issue with Webhooks as ShadowJar isn't from it, but a separate thing.

how might I do that?
sorry if stupid questioon
