### ISSUE TITLE
Getting NoClassDefFound on every single dependencies the API has

### ISSUE THREAD

**Issue by Cocolennon** [MinnDevelopment/discord-webhooks#70]
Basically, everytime I shadein one of discord-webhooks' dependencies, I get NoClassDefFound on another.
It started with org.json.JSONString then okhttp3.okhttp and finally okio.BufferedSource, then no matter what I do with okio, it stays stuck there

**Comment by MinnDevelopment** [comment]
This sounds like an issue with your build setup. The library correctly configures api and implementation dependencies.

It is recommended to use gradle or maven to build your project.
