### ISSUE TITLE
How do I cast to EmbedAuthor?

### ISSUE THREAD

**Issue by xzntrc** [MinnDevelopment/discord-webhooks#71]
Why can't WebhookEmbedBuilder().setAuthor() accept a string? I'm looking at the docs and it must be EmbedAuthor type, I've tried casting but I don't understand how to.

**Comment by Andre601** [comment]
Did you check the readme?

**Comment by xzntrc** [comment]
I created it. Well, there is no refrence of author in it. so I figured it would be a type. Sorry.
