### ISSUE TITLE
Not compatible anymore with JDA 5.0.0

### ISSUE THREAD

**Issue by RedsTom** [MinnDevelopment/discord-webhooks#76]
With the changes made to DataMessage by JDA for its version 5, the library does not work anymore

**Comment by srnyx** [comment]
@MinnDevelopment Is there an ETA for this?

**Comment by MinnDevelopment** [comment]
I'm currently kind of swamped with work. If anyone wants to open a PR with the necessary changes, I can take a look this weekend.

**Comment by srnyx** [comment]
> I'm currently kind of swamped with work. If anyone wants to open a PR with the necessary changes, I can take a look this weekend.

https://github.com/MinnDevelopment/discord-webhooks/pull/78

**Comment by MinnDevelopment** [comment]
Resolved by #88
