### ISSUE TITLE
[Question] How does the lib handle rate limits

### ISSUE THREAD

**Issue by Andre601** [MinnDevelopment/discord-webhooks#81]
I'm curious to know how exactly this library handles rate limits. By that I mean the following questions:

- How does it set/obtain rate limit information. Is it a hard-coded value it gets from somewhere in the lib itself? Is it retrieved from something like a response header from discord?
- How exactly does it handle new requests when the current rate limit is used up? Simply queue them for future sending? Print warns?

I'm asking this because a software I use (A plugin) uses this library. And whenever there is a large number of text to be send through a webhook is the WebhookClient encountering 429 errors and prints those in the console:

![errors](https://cdn.discordapp.com/attachments/817518771233095741/1105926030369230930/image.png)

According to the dev, and from my own checks, is the library used as it should. A single WebhookClient instance is created and used for a single webhook without recreating it during the entire use.

What could be possible causes for this random issue?

**Comment by MinnDevelopment** [comment]
Rate-Limits are handled here:

https://github.com/MinnDevelopment/discord-webhooks/blob/e7e5db7d2d4cc690d9a26fedd23bd998821ff402/src/main/java/club/minnced/discord/webhook/WebhookClient.java#L909-L930

When a rate-limit is hit, the requests are scheduled here:

https://github.com/MinnDevelopment/discord-webhooks/blob/e7e5db7d2d4cc690d9a26fedd23bd998821ff402/src/main/java/club/minnced/discord/webhook/WebhookClient.java#L790-L795

This happens both on [new requests](https://github.com/MinnDevelopment/discord-webhooks/blob/e7e5db7d2d4cc690d9a26fedd23bd998821ff402/src/main/java/club/minnced/discord/webhook/WebhookClient.java#L772-L778) and [queued requests](https://github.com/MinnDevelopment/discord-webhooks/blob/e7e5db7d2d4cc690d9a26fedd23bd998821ff402/src/main/java/club/minnced/discord/webhook/WebhookClient.java#L844-L846).

What you might be observing here is a sub-resource limit.

**Comment by Andre601** [comment]
> What you might be observing here is a sub-resource limit.

Sub-resource limit? Never heard of that before. Any way to prevent such an issue.

**Comment by MinnDevelopment** [comment]
There is no way to prevent sub-resource limits. You just have to slow down requests.
