### ISSUE TITLE
Using Components

### ISSUE THREAD

**Issue by thauanvargas** [MinnDevelopment/discord-webhooks#89]
Hello I've just started using this library, but I don't find anyway of adding Components to the webhook message, is this possible?

I need to add a button to the last sent webhook message, patching last one if it was sent before.

**Comment by MinnDevelopment** [comment]
Components can only be used by bots and application owned webhooks. However, there is a PR to support them in those cases #73

**Comment by MinnDevelopment** [comment]
Closing as duplicate of #46
