### ISSUE TITLE
HTTP Error while sending webhook

### ISSUE THREAD

**Issue by TheSilentPro** [MinnDevelopment/discord-webhooks#9]
I get this error when trying to send a webhook:
https://hastebin.com/ahepibayab.bash

this is the builder:
https://hastebin.com/otagozirev.coffeescript

`url: 'https://discordapp.com/api/webhooks/706515879516569630/kISL0f2CNrJe4LbgUu2V9ML85FODJgJtrFG6qtIyc7qGANwxvUq11dxJyumd_zwiIN3c'
`

**Comment by MinnDevelopment** [comment]
Looks like you're sending an invalid URL. What is your code for sending?

**Comment by TheSilentPro** [comment]
It's the 'url' value at the bottom of the issue.
This: `https://discordapp.com/api/webhooks/706515879516569630/kISL0f2CNrJe4LbgUu2V9ML85FODJgJtrFG6qtIyc7qGANwxvUq11dxJyumd_zwiIN3c`

**Comment by TheSilentPro** [comment]
Oh you mean this:
https://hastebin.com/owaperonof.js
sorry my bad.

**Comment by MinnDevelopment** [comment]
It looks like both of your URL's in the EmbedAuthor are invalid.

**Comment by kantenkugel** [comment]
The iconUrl, url of the Author, the iconUrl of the Footer and the url of the embed all seem to be invalid, which in your code would correspond to `FileUtils.getString("webhook.author.iconurl", ...)`, `FileUtils.getString("webhook.author.url", ...)` `FileUtils.getString("webhook.footer.icon", ...)`, `FileUtils.getString("webhook.title.url", ...)`

make sure those are correct urls (and in case of images being urls to images).
You can just print them if you are not sure what their content is

**Comment by TheSilentPro** [comment]
Okay i will add null checks for them
I would have thought that if the provided string is null or empty it just would not set it

**Comment by kantenkugel** [comment]
null might be valid, empty string not. but you should be able to figure that out from docs

**Comment by TheSilentPro** [comment]
Would setting one of them to null still send it without prob?
For example setting author to ("Author", null, null)

**Comment by kantenkugel** [comment]
That one i told you to look up in the docs. Buf for the lazy ones (and since theres no hosted javadocs): <https://github.com/MinnDevelopment/discord-webhooks/blob/c2e51c50acc203208e3ac69d19b7ce1803f08f6e/src/main/java/club/minnced/discord/webhook/send/WebhookEmbed.java#L307-L318>

**Comment by xXBuilderBXx** [comment]
@kantenkugel @TheSilentPro you do realize that you just sent the id and token of a webhook.... and that anyone can use this to abuse it by sending god knows what and also bypasses ping perms....

**Comment by TheSilentPro** [comment]
@xXBuilderBXx yes i know, i regenerated it when i created the issue
